salesforce-app/src/objects/Channel__c.object
<CustomObject>
    <description>The object used to keep track of all details related to channels</description>
    <fields>
        <fullName>ExtId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <picklist>
            <picklistValues>
                <fullName>Dailymotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youtube</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-app/src/objects/CurrencyTable__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate__c</fullName>
        <label>Conversion Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ValidDate__c</fullName>
        <label>Valid Date</label>
        <type>Date</type>
    </fields>
    <label>Currency Table</label>
    <nameField>
        <label>Currency Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-app/src/objects/MarketerStatistics__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Ref__c</fullName>
        <label>Channel Reference</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Marketer Statistics</relationshipLabel>
        <relationshipName>Marketer_Statistics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Marketer__c</fullName>
        <label>Marketer</label>
        <picklist>
            <picklistValues>
                <fullName>Youtube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XYZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cMedia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>1988</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1989</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1990</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketer Statistics</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Marketer Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketer Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-app/src/objects/RevenueData__c.object
<CustomObject>
    <fields>
        <fullName>ChannelExtId__c</fullName>
        <externalId>true</externalId>
        <label>Channel External Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConversionRate_Ref__c</fullName>
        <label>Conversion Rate Reference</label>
        <referenceTo>CurrencyTable__c</referenceTo>
        <relationshipLabel>Revenue Data</relationshipLabel>
        <relationshipName>Revenue_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MarketerStatistics_Ref__c</fullName>
        <label>Marketer Statistics Reference</label>
        <referenceTo>MarketerStatistics__c</referenceTo>
        <relationshipLabel>Revenue Data</relationshipLabel>
        <relationshipName>Revenue_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketer__c</fullName>
        <label>Marketer</label>
        <picklist>
            <picklistValues>
                <fullName>Youtube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XYZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cMedia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ValidDate__c</fullName>
        <label>Valid Date</label>
        <type>Date</type>
    </fields>
    <label>Revenue Data</label>
    <nameField>
        <label>Revenue Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-app/src/classes/RevenueDataTH.cls
/**
 * Handler class to handle all logic for Revenue Data trigger
 *
 * @author Aditi Satpute
 */
public with sharing class RevenueDataTH {

    /**
     * Main trigger handling logic to be called from Revenue Data trigger
     */
    public static void triggerHandler(
            Boolean isBefore,
            Boolean isAfter,
            Boolean isInsert,
            Boolean isUpdate,
            Boolean isDelete,
            List<RevenueData__c> newRecords,
            Map<Id, RevenueData__c> oldRecordsMap
    ) {
        if (isBefore) {
            beforeHandler(isInsert, isUpdate, isDelete, newRecords, oldRecordsMap);
        }
    }

    /**
     * Before trigger handler to redirect properly based on insert, update or delete
     */
    private static void beforeHandler(
            Boolean isInsert,
            Boolean isUpdate,
            Boolean isDelete,
            List<RevenueData__c> newRecords,
            Map<Id, RevenueData__c> oldRecordsMap
    ) {
        if (isInsert) {
            beforeInsert(newRecords);
        }
    }

    /**
     * Before insert logic
     */
    private static void beforeInsert(List<RevenueData__c> newRecords) {
        setAlignmentForRevenueData(newRecords);
    }

    /**
     * Method to set all alignment for Revenue Data
     *   - Set Channel alignment
     *   - Set MarketerStatistics alignment
     *   - Set Channel Data alignment
     * @param newRevenueDataList List of Revenue data that needs to be inserted
     */
    private static void setAlignmentForRevenueData(List<RevenueData__c> newRevenueDataList) {

      /*  List<String> splitDateDetails = new List<String>();

        // Fetch all the details of Channels
        List<Channel__c> channelList = [
            SELECT
                Id,
                Name,
                ExtId__c,
                Platform__c
            FROM
                Channel__c
        ];

        // Fetch details of Marketer Statistics
        List<MarketerStatistics__c> marketerStatisticsList = [
            SELECT
                Id,
                Name,
                Channel_Ref__c,
                Channel_Ref__r.ExtId__c,
                Marketer__c,
                Month__c,
                Year__c
            FROM
                MarketerStatistics__c
        ];

        // Fetch details of Currency Table
        List<CurrencyTable__c> currencyTableList = [
            SELECT
                Id,
                Name,
                Conversion_Rate__c,
                Currency_Code__c,
                ValidDate__c
            FROM
                CurrencyTable__c
            ORDER BY
                ValidDate__c DESC
        ];

        // Prepare a Map with External Id of Channel as its Key along with its instance
        Map<String, Channel__c> mapChannelExtIdToInstance = new Map<String, Channel__c>();
        for (Channel__c channelInstance : channelList) {
            mapChannelExtIdToInstance.put(channelInstance.ExtId__c, channelInstance);
        }
        System.debug('--mapChannelExtIdToInstance--->' + mapChannelExtIdToInstance);

        // Prepare a Map with External Id of Marketer statistics channel as its Key along with its instance
        Map<String, MarketerStatistics__c> mapMarketerStatisticsChannelExtIdToInstance =
            new Map<String, MarketerStatistics__c>();
        Map<String, MarketerStatistics__c> mapMarketerStatisticsChannelExtIdToInstanceToInsert =
            new Map<String, MarketerStatistics__c>();

        for (MarketerStatistics__c marketerStatisticsInstance : marketerStatisticsList) {
            mapMarketerStatisticsChannelExtIdToInstance.put(
                marketerStatisticsInstance.Channel_Ref__r.ExtId__c,
                marketerStatisticsInstance
            );
        }
        System.debug('--mapMarketerStatisticsChannelExtIdToInstance--->'
            + mapMarketerStatisticsChannelExtIdToInstance
        );

        // Prepare a Map with Currency code as its key along with Value as List of instances
        // sorted in descending order with respect to Valid Date
        Map<string, List<CurrencyTable__c>> mapCurrencyCodeToCurrencyList =
            new Map<string, List<CurrencyTable__c>>();
        for (CurrencyTable__c currencyTableInstance : currencyTableList) {
            if (mapCurrencyCodeToCurrencyList.containsKey(currencyTableInstance.Currency_Code__c)) {
                List<CurrencyTable__c> existingCurrencyTableList =
                    mapCurrencyCodeToCurrencyList.get(currencyTableInstance.Currency_Code__c);
                existingCurrencyTableList.add(currencyTableInstance);
                mapCurrencyCodeToCurrencyList.put(
                    currencyTableInstance.Currency_Code__c,
                    existingCurrencyTableList
                );
            } else {
                mapCurrencyCodeToCurrencyList.put(
                    currencyTableInstance.Currency_Code__c,
                    new List<CurrencyTable__c> {currencyTableInstance}
                );
            }
        }
        System.debug('--mapCurrencyCodeToCurrencyList--->' + mapCurrencyCodeToCurrencyList);

        // Iterate over the Revenue Data List that is being inserted
        for (RevenueData__c revenuedataInstance : newRevenueDataList) {

            // Verify the channel is present for the revenue data
            if (mapChannelExtIdToInstance.containsKey(revenuedataInstance.channelExtId__c)) {
                Channel__c channelInstance =
                    mapChannelExtIdToInstance.get(revenuedataInstance.channelExtId__c);

                if (revenuedataInstance.validDate__c != null) {
                    splitDateDetails =
                        String.valueOf(revenuedataInstance.validDate__c).split('-');
                    System.debug('---splitDateDetails--->'+splitDateDetails);
                }

                // Verify the Marketer Statistics record for the linked channel is
                // present for the revenue data
                if (mapMarketerStatisticsChannelExtIdToInstance.containsKey(
                        revenuedataInstance.channelExtId__c
                )) {
                    MarketerStatistics__c marketerStatisticsInstance =
                        mapMarketerStatisticsChannelExtIdToInstance.get(
                            revenuedataInstance.channelExtId__c
                        );
                    System.debug('--->In if');

                    // Verify that the Marketer statistics have same Marketer as the Revenue Data
                    if (revenuedataInstance.Marketer__c == marketerStatisticsInstance.Marketer__c) {

                        // Find the Marketer Statistic record based on Month and Year
                        // and align it to revenue data
                        if (
                                splitDateDetails.size() == 3
                                && marketerStatisticsInstance.Month__c == splitDateDetails[1].trim()
                                && marketerStatisticsInstance.Year__c == splitDateDetails[0].trim()
                        ) {
                            revenuedataInstance.MarketerStatistics_Ref__c =
                                marketerStatisticsInstance.Id;
                        } else {
                            revenuedataInstance.addError(
                                'No Marketer Statistics record present for Month "'
                                    + splitDateDetails[1].trim() + '" and Year "'
                                    + splitDateDetails[0].trim() + '"'
                            );
                        }
                    } else {
                        System.debug('--->In else');
                        revenuedataInstance.addError(
                            'No Marketer Statistics record present for Marketer "'
                                + revenuedataInstance.Marketer__c + '"'
                        );
                    }
                } else {

                    // If Marketer Statistics record not found for the specified Channel
                    // External Id then create new Marketer Statistics record
                    MarketerStatistics__c marketerStatisticsInstance = new MarketerStatistics__c();
                    if (splitDateDetails.size() == 3) {
                        marketerStatisticsInstance.Month__c = splitDateDetails[1].trim();
                        marketerStatisticsInstance.Year__c = splitDateDetails[0].trim();
                        marketerStatisticsInstance.Marketer__c = revenuedataInstance.Marketer__c;
                        marketerStatisticsInstance.Channel_Ref__c = channelInstance.Id;
                        mapMarketerStatisticsChannelExtIdToInstanceToInsert.put(
                            channelInstance.ExtId__c,
                            marketerStatisticsInstance
                        );
                    }
                }
            }

            // Set the Currency Table linking for respective revenue data
            if (mapCurrencyCodeToCurrencyList.containsKey(revenuedataInstance.Currency__c)) {
                List<CurrencyTable__c> currencyTableListDetails =
                    mapCurrencyCodeToCurrencyList.get(revenuedataInstance.Currency__c);
                for (CurrencyTable__c currencyTableInstance :
                        mapCurrencyCodeToCurrencyList.get(revenuedataInstance.Currency__c)
                ) {
                    if (currencyTableInstance.validDate__c == revenuedataInstance.validDate__c) {
                        revenuedataInstance.ConversionRate_Ref__c = currencyTableInstance.Id;
                    }
                }

                // If no valid Data found related to Currency Table then link with the newest Record
                if (
                        revenuedataInstance.ConversionRate_Ref__c == null
                        && currencyTableListDetails.size() > 0
                ) {
                    revenuedataInstance.ConversionRate_Ref__c =
                        currencyTableListDetails[currencyTableListDetails.size() - 1].Id;
                }
            }
        }

        System.debug('--mapMarketerStatisticsChannelExtIdToInstanceToInsert--->'
            + mapMarketerStatisticsChannelExtIdToInstanceToInsert
        );
        // Insert the Marketer Statistics records whose channels are present for the revenue data
        if (mapMarketerStatisticsChannelExtIdToInstanceToInsert.size() > 0) {
            Database.SaveResult[] saveResultList =
                Database.insert(
                    mapMarketerStatisticsChannelExtIdToInstanceToInsert.values(),
                    false
                );

            // Iterate over the revenue data to align proper linking between newly inserted
            // Marketer Statistics to revenue data
            for (RevenueData__c revenuedataInstance : newRevenueDataList) {
                if (mapMarketerStatisticsChannelExtIdToInstanceToInsert.containsKey(
                        revenuedataInstance.channelExtId__c
                )) {
                        MarketerStatistics__c marketerStatisticsInstance =
                            mapMarketerStatisticsChannelExtIdToInstanceToInsert.get(
                                revenuedataInstance.channelExtId__c
                            );
                        if (marketerStatisticsInstance != null) {
                            revenuedataInstance.MarketerStatistics_Ref__c =
                                marketerStatisticsInstance.Id;
                        }
                }
            }
        }
        System.debug('--newRevenueDataList--->' + newRevenueDataList);*/
    }
}